---
abstract: 'SDL Extensions for UAV::Pilot'
author:
  - 'Timm Murray <tmurray@wumpus-cave.net>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UAV-Pilot-SDL
provides:
  MockSDL:
    file: lib/UAV/Pilot/SDL/Window/Mock.pm
    version: 0
  UAV::Pilot::SDL:
    file: lib/UAV/Pilot/SDL.pm
    version: 0.1
  UAV::Pilot::SDL::Events:
    file: lib/UAV/Pilot/SDL/Events.pm
    version: 0
  UAV::Pilot::SDL::Joystick:
    file: lib/UAV/Pilot/SDL/Joystick.pm
    version: 0
  UAV::Pilot::SDL::NavFeeder:
    file: lib/UAV/Pilot/SDL/NavFeeder.pm
    version: 0
  UAV::Pilot::SDL::Video:
    file: lib/UAV/Pilot/SDL/Video.pm
    version: 0
  UAV::Pilot::SDL::VideoOverlay:
    file: lib/UAV/Pilot/SDL/VideoOverlay.pm
    version: 0
  UAV::Pilot::SDL::VideoOverlay::Reticle:
    file: lib/UAV/Pilot/SDL/VideoOverlay/Reticle.pm
    version: 0
  UAV::Pilot::SDL::Window:
    file: lib/UAV/Pilot/SDL/Window.pm
    version: 0
  UAV::Pilot::SDL::Window::Mock:
    file: lib/UAV/Pilot/SDL/Window/Mock.pm
    version: 0
  UAV::Pilot::SDL::WindowEventHandler:
    file: lib/UAV/Pilot/SDL/WindowEventHandler.pm
    version: 0
requires:
  AnyEvent: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Event: 0
  SDL: 0
  Test::More: 0
  UAV::Pilot: 0.9
  namespace::autoclean: 0
  perl: v5.14.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository: https://github.com/frezik/UAV-Pilot-SDL
version: 0.1
